### ISSUE TITLE
imgadm-repair seems to be broken

### ISSUE THREAD

**Issue by MerlinDMC** [joyent/smartos-live#129]
on platform version joyent_20121004T212912Z

```
[root@00-0c-29-18-ec-10 ~]# /usr/img/sbin/imgadm-repair
Checking for manifest with UUID: $i
$i - manifest was found. Copying to $DBDIR
json: error: input is not JSON: Unexpected '$' at line 1, column 1:
        ${manifest}
        ^
$i - urn: $urn
[root@00-0c-29-18-ec-10 ~]# imgadm info 01b2c898-945f-11e1-a523-af1afbe22822

undefined:1
${manifest}
^
SyntaxError: Unexpected token $
    at Object.parse (native)
    at db.load (/usr/img/node_modules/db.js:182:37)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

funny about that is that even with the error the cachefile gets updated:
```
[root@00-0c-29-18-ec-10 ~]# cat /var/db/imgadm/01b2c898-945f-11e1-a523-af1afbe22822.json
${manifest}
```

now `imgadm list` ect. is not working anymore

**Comment by bahamas10** [comment]
@MerlinDMC ^ same question as #130 ... still relevant?
