### ISSUE TITLE
imgadm avail fails in smartos-20130503T001121Z-USB.img

### ISSUE THREAD

**Issue by brdloush** [joyent/smartos-live#211]
Fresh install, just after 1st reboot. Networking worked fine. I issued `imgadm update`. It finished quite quickly without any complains. Then I performed `imgadm avail`. It took some time and then crashed with  following exception:

[root@00-1e-8c-8e-3b-80 ~]# imgadm avail

/usr/img/lib/imgadm.js:1102
                for (var j = 0; j < imageSet.length; j++) {
                                            ^
TypeError: Cannot read property 'length' of undefined
    at done (/usr/img/lib/imgadm.js:1102:45)
    at async.forEach (/usr/img/node_modules/async/lib/async.js:88:21)
    at IMGADM.sourcesList.async.forEach.err (/usr/img/lib/imgadm.js:1080:21)
    at IMGADM.clientFromSource (/usr/img/lib/imgadm.js:744:13)
    at Source.getResolvedUrl (/usr/img/lib/imgadm.js:361:13)
    at /usr/img/lib/imgadm.js:98:13
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete](dns.js:124:7)

The workaround was to reboot into usb stick with older image (smartos-20130419T073558Z-USB.img.bz2). On this image, `imgadm avail` worked ok.

**Comment by bahamas10** [comment]
@brdloush is this still an issue?
