### ISSUE TITLE
Mercurial fails with osutil.so: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by jessegit** [joyent/smartos-live#398]
zone based on
22d0698e-6e98-11e4-97ca-470617ccfeae  multiarch     14.3.0   smartos  2014-11-17T20:27:22Z

```shell
# pkgin update
# pkgin -y full-upgrade
# pkgin -y in mercurial

[root@multi143 ~]# uname -a
SunOS multi143 5.11 joyent_20141002T182809Z i86pc i386 i86pc Solaris
[root@multi143 ~]# hg --version
Traceback (most recent call last):
  File "/opt/local/bin/hg", line 41, in <module>
    mercurial.util.setbinary(fp)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 106, in __getattribute__
    self._load()
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 78, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 47, in _hgextimport
    return importfunc(name, globals, *args)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/util.py", line 67, in <module>
    statfiles = getattr(osutil, 'statfiles', platform.statfiles)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 106, in __getattribute__
    self._load()
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 78, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 47, in _hgextimport
    return importfunc(name, globals, *args)
ImportError: ld.so.1: python2.7: fatal: /opt/local/lib/python2.7/site-packages/amd64/mercurial/osutil.so: wrong ELF class: ELFCLASS64
```

**Comment by jessegit** [comment]
```
# file `which python2.7`
/opt/local/bin/python2.7:       ELF 32-bit LSB executable 80386 Version 1 [FPU], dynamically linked, not stripped, no debugging information available
```
that would explain it?

**Comment by jperkin** [comment]
No, that will be a hardlink to abiexec, which will call the appropriate python2.7 binary based on your ABI setting (so either `/opt/local/bin/i86/python2.7` or `/opt/local/bin/amd64/python2.7`).  I'll take a look at this on Monday.

**Comment by JonStrabala** [comment]
Given the issue described above:

```
[root@gcc01 /root]# hg
ImportError: ld.so.1: python2.7: fatal: /opt/local/lib/python2.7/site-packages/amd64/mercurial/osutil.so: wrong ELF class: ELFCLASS64
```
Here is a deplorable "hack" for a quick workaround 
```
[root@gcc01 /root]# mv /opt/local/lib/python2.7/site-packages/amd64 /opt/local/lib/python2.7/site-packages/amd64.orig
[root@gcc01 /root]# cd /opt/local/lib/python2.7/site-packages/
[root@gcc01 /opt/local/lib/python2.7/site-packages]# mkdir amd64
[root@gcc01 /opt/local/lib/python2.7/site-packages]# cd amd64
[root@gcc01 /opt/local/lib/python2.7/site-packages/amd64]# ln -s ../mercurial .
```

Now you can launch Mercurial via 'hg' as expected

```
[root@gcc01 /opt/local/lib/python2.7/site-packages/amd64]# hg
Mercurial Distributed SCM

basic commands:

 add           add the specified files on the next commit
 annotate      show changeset information by line for each file
 clone         make a copy of an existing repository
 commit        commit the specified files or all outstanding changes
 diff          diff repository (or selected files)
 export        dump the header and diffs for one or more changesets
 forget        forget the specified files on the next commit
 init          create a new repository in the given directory
 log           show revision history of entire repository or files
 merge         merge another revision into working directory
 pull          pull changes from the specified source
 push          push changes to the specified destination
 remove        remove the specified files on the next commit
 serve         start stand-alone webserver
 status        show changed files in the working directory
 summary       summarize working directory state
 update        update working directory (or switch revisions)

(use "hg help" for the full list of commands or "hg -v" for details)
[root@gcc01 /opt/local/lib/python2.7/site-packages/amd64]#
```
