### ISSUE TITLE
Unable to restart metadata, vminfod and vmadmd after crashing

### ISSUE THREAD

**Issue by youzhongyang** [joyent/smartos-live#825]
```
# svcs -pv vminfod vmadmd metadata
STATE          NSTATE        STIME    CTID   FMRI
online         -             Jan_22       66 svc:/system/smartdc/vminfod:default
online         -             Jan_22      126 svc:/system/smartdc/metadata:default
online         -             Jan_22      215 svc:/system/smartdc/vmadmd:default
# ls -l /zones/global/cores/
total 73845
-rw-------   1 root     root     50587369 Jan 28 05:56 core.metadata.6307
-rw-------   1 root     root     68628529 Jan 28 05:56 core.vmadmd.6785
-rw-------   1 root     root     74068745 Jan 28 05:56 core.vminfod.5640
# svcadm restart vminfod
# svcs -pv vminfod
STATE          NSTATE        STIME    CTID   FMRI
online         -             Jan_22       66 svc:/system/smartdc/vminfod:default
# vmadm list
connect ECONNREFUSED
```
I don't know why all of them crashed at the same time. As a workaound, manually starting all of the 3  (/usr/vm/sbin/metadata, /usr/vm/sbin/vminfod and /usr/vm/sbin/vmadmd) works, but it looks like a bug to me that service restarting of metadata, vminfod and vmadmd doesn't work.

**Comment by jclulow** [comment]
It would help to look in the log files for the services (you can get the path with, e.g., `svcs -L vminfod`).  You can also look at the log for SMF itself; i.e., `/var/svc/log/svc.startd.log`.

**Comment by youzhongyang** [comment]
not much hint of what went wrong:
```
# ls -l /var/svc/log/system-smartdc-vminfod\:default.log
-rw-r--r--   1 root     root           0 Jan 29 13:00 /var/svc/log/system-smartdc-vminfod:default.log

# tail -6 /var/svc/log/svc.startd.log
Jan 22 16:14:04/6: instance svc:/site/recursive_hsreplicate:default exited with status 1
Jan 22 16:14:04/6: instance svc:/site/recursive_hsreplicate:default exited with status 1
Jan 22 16:14:04/6: instance svc:/site/recursive_hsreplicate:default exited with status 1
Jan 22 16:14:04/6: instance svc:/site/recursive_hsreplicate:default exited with status 1
Jan 28 05:55:33/1: restarting after interruption
Jan 28 05:55:33/1: restarting after interruption
```

**Comment by jclulow** [comment]
The timestamp on the file is the top of the hour -- has the log for `vminfod` been rotated?  Check with: `ls /var/svc/log/*vminfod* /var/log/sdc/upload/*vminfod*`

**Comment by youzhongyang** [comment]
Now it starts to make sense. svc.startd died possibly due to internal network outage.

```
# ls -la /var/svc/log/*vminfod*
-rw-r--r--   1 root     root           0 Jan 29 13:00 /var/svc/log/system-smartdc-vminfod:default.log

# ls -la /var/log/sdc/upload
total 2
drwxr-xr-x   2 root     sys            2 Aug 21 16:28 .
drwxr-xr-x   3 root     sys            3 Aug 23 16:45 ..

# svcs fmd
STATE          STIME    FMRI
online         Jan_22   svc:/system/fmd:default

# svcadm restart fmd

# svcs fmd
STATE          STIME    FMRI
online         Jan_22   svc:/system/fmd:default

# cat /var/adm/messages
Jan 28 05:55:14 batfs1399 sshd[5946]: [ID 800047 auth.error] error: fork: Resource temporarily unavailable
Jan 28 05:55:33 batfs1399 svc.startd[99693]: [ID 152077 daemon.notice] restarting after interruption
Jan 28 05:55:33 batfs1399 svc.startd[99698]: [ID 152077 daemon.notice] restarting after interruption
Jan 28 06:16:04 batfs1399 sshd[5946]: [ID 800047 auth.error] error: fork: Resource temporarily unavailable
Jan 28 06:29:08 batfs1399 winbindd[5730]: [ID 702911 daemon.warning] [2019/01/28 06:29:08.872007,  1, pid=5730] ../source3/lib/messages.c:1455(mess_parent_dgm_cleanup_done)
Jan 28 06:29:08 batfs1399 winbindd[5730]: [ID 702911 daemon.warning]   messaging dgm cleanup job ended with NT_STATUS_NETWORK_BUSY

# svcs -pv /system/svc/restarter
STATE          NSTATE        STIME    CTID   FMRI
online         -             Jan_28    64627 svc:/system/svc/restarter:default
```

**Comment by rmaiquez** [comment]
Hi, 
it's happend to me also.

I upgraded the smartos server to latest version and when rebooted system these services not working, **metadata** and **vmadmd** are on status `offline` and **vminfod** is status `manteinance`.

I try get log but only have `metadata`
```
# svcs -pv vminfod vmadmd metadata
STATE          NSTATE        STIME    CTID   FMRI
offline        -             22:36:31    239 svc:/system/smartdc/metadata:default
offline        -             22:36:31    236 svc:/system/smartdc/vmadmd:default
maintenance    -             22:36:17      - svc:/system/smartdc/vminfod:default

# tail -25 /var/svc/log/system-smartdc-metadata:default.log
[ Oct 14 22:36:13 Method "start" exited with status 0. ]
{"name":"metadata","hostname":"smartos","pid":7478,"client":"Metadata Agent - VminfodWatcher","level":50,"err":{"message":"connect ECONNREFUSED","name":"Error","stack":"Error: connect ECONNREFUSED\n    at errnoException (net.js:907:11)\n    at Object.afterConnect [as oncomplete] (net.js:898:19)","code":"ECONNREFUSED"},"msg":"VminfodEventStream request error","time":"2019-10-14T22:36:13.975Z","v":0}
{"name":"metadata","hostname":"smartos","pid":7478,"client":"Metadata Agent - VminfodWatcher","level":20,"msg":"vminfod event stream stopped","time":"2019-10-14T22:36:13.977Z","v":0}
Uncaught Error: connect ECONNREFUSED

FROM
VminfodEventStream.EventEmitter.emit (events.js:72:15)
VminfodEventStream._vminfodEventStreamAbort [as _abort] (/usr/vm/node_modules/vminfod/client.js:581:10)
ClientRequest.reqError (/usr/vm/node_modules/vminfod/client.js:467:14)
ClientRequest.EventEmitter.emit (events.js:95:17)
Socket.socketErrorListener (http.js:1545:9)
Socket.EventEmitter.emit (events.js:95:17)
net.js:443:14
process._tickCallback (node.js:415:13)
[ Oct 14 22:36:31 Stopping because all processes in service exited. ]
[ Oct 14 22:36:31 Executing stop method (:kill). ]
```

for vmadmd and vminfod logs are empty.

can you help me?
