### ISSUE TITLE
Unable to restart metadata, vminfod and vmadmd after upgrade smartos

### ISSUE THREAD

**Issue by rmaiquez** [joyent/smartos-live#852]
Hello,

I upgraded yesterday the smartos server to latest version and when rebooted system these services not working, **metadata** and **vmadmd** are on status `offline` and **vminfod** is status `manteinance`.

I try get log but only have `metadata`
```
# svcs -pv vminfod vmadmd metadata
STATE          NSTATE        STIME    CTID   FMRI
offline        -             22:36:31    239 svc:/system/smartdc/metadata:default
offline        -             22:36:31    236 svc:/system/smartdc/vmadmd:default
maintenance    -             22:36:17      - svc:/system/smartdc/vminfod:default

# tail -25 /var/svc/log/system-smartdc-metadata:default.log
[ Oct 14 22:36:13 Method "start" exited with status 0. ]
{"name":"metadata","hostname":"smartos","pid":7478,"client":"Metadata Agent - VminfodWatcher","level":50,"err":{"message":"connect ECONNREFUSED","name":"Error","stack":"Error: connect ECONNREFUSED\n    at errnoException (net.js:907:11)\n    at Object.afterConnect [as oncomplete] (net.js:898:19)","code":"ECONNREFUSED"},"msg":"VminfodEventStream request error","time":"2019-10-14T22:36:13.975Z","v":0}
{"name":"metadata","hostname":"smartos","pid":7478,"client":"Metadata Agent - VminfodWatcher","level":20,"msg":"vminfod event stream stopped","time":"2019-10-14T22:36:13.977Z","v":0}
Uncaught Error: connect ECONNREFUSED

FROM
VminfodEventStream.EventEmitter.emit (events.js:72:15)
VminfodEventStream._vminfodEventStreamAbort [as _abort] (/usr/vm/node_modules/vminfod/client.js:581:10)
ClientRequest.reqError (/usr/vm/node_modules/vminfod/client.js:467:14)
ClientRequest.EventEmitter.emit (events.js:95:17)
Socket.socketErrorListener (http.js:1545:9)
Socket.EventEmitter.emit (events.js:95:17)
net.js:443:14
process._tickCallback (node.js:415:13)
[ Oct 14 22:36:31 Stopping because all processes in service exited. ]
[ Oct 14 22:36:31 Executing stop method (:kill). ]
```

for vmadmd and vminfod logs are empty.

I tried this https://github.com/joyent/smartos-live/issues/825 but not working for me.

can anybody help me?

**Comment by rmaiquez** [comment]
Ok, It's resolved to me.

My problem was that something has gone wrong with instance <<uuid-zone>>

I do:
```bash
zfs mount -a
svcadm clear vminfod
```
but that doesn't fixed it, so:
```bash
zfs get all zones/<<uuii-zone>>
find /zones/<<uuii-zone>>
```
that dataset doesn't existed, somehow a zone configuration remained after <<uuid-zone>> was destroyed.  Thats instate was partially deleted, so I removed the zone configuration with:
```bash
zonecfg -z <<uuid-zone>>  delete
```
Then:
```bash
svcadm clear vminfod
```

And all working normal now
